services:
  server:
    build: .
    image: node-app
    ports: 
      - "8081:8080"
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'postgres'
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
  